theme = "catppuccin_mocha"

[editor]
line-number = "relative"
mouse = false
rulers = [120]
shell = ["pwsh.exe", "-NoLogo -NoProfile -ExecutionPolicy RemoteSigned -Command [Console]::InputEncoding=[Console]::OutputEncoding=[System.Text.Encoding]::UTF8;"]

[editor.file-picker]
hidden = false