theme = "base16_transparent"

[editor]
bufferline = "always"
color-modes = true
cursorline = true
# default-line-ending = "lf"
line-number = "relative"
mouse = false
rulers = [120]
shell = [
  "pwsh.exe",
  "-NoLogo -NoProfile -ExecutionPolicy RemoteSigned -Command [Console]::InputEncoding=[Console]::OutputEncoding=[System.Text.Encoding]::UTF8;",
]
text-width = 120
true-color = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.gutters.line-numbers]
min-width = 1

[editor.indent-guides]
render = false
character = "┊" # Some characters that work well: "╎", "▏", "┆", "┊", "⸽"
skip-levels = 1

[editor.lsp]
display-inlay-hints = true
