name: Setup Workflow

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest]
    steps:
    - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
    - name: Run curl Setup
      run: curl https://raw.githubusercontent.com/Coordinate-Cat/dotfiles/master/install.sh
    - name: Run dotfiles setup
      run: /bin/bash install.sh